### ISSUE TITLE
Loadcell type

### ISSUE THREAD

**Issue by baldisos** [ChrGri/DIY-Sim-Racing-FFB-Pedal-Mechanical-Design#2]
The info on the Loadcell says "200kg", but when opening the Amazon link (Germany) i can only choose between 50kg, 100kg, 300kg and 2000kg.
Is the Loadcell really a 200kg one, or is that 2000kg?

![grafik](https://github.com/user-attachments/assets/121b46ad-7beb-4648-b4d7-0b46dff75ebb)

**Comment by ChrGri** [comment]
Thanks for letting me know. If corrected the link.
