### ISSUE TITLE
Alternative linear guide

### ISSUE THREAD

**Issue by dabohda** [ChrGri/DIY-Sim-Racing-FFB-Pedal-Mechanical-Design#3]
This could be a better linear guide because of the aditional bearing: [Link](https://de.aliexpress.com/item/1005007575672349.html?spm=a2g0o.detail.pcDetailTopMoreOtherSeller.5.461bYOfnYOfnG7&gps-id=pcDetailTopMoreOtherSeller&scm=1007.40050.354490.0&scm_id=1007.40050.354490.0&scm-url=1007.40050.354490.0&pvid=c97f7a1e-310d-4beb-ba1e-c63ddc850a95&_t=gps-id:pcDetailTopMoreOtherSeller,scm-url:1007.40050.354490.0,pvid:c97f7a1e-310d-4beb-ba1e-c63ddc850a95,tpp_buckets:668%232846%238115%232000&pdp_npi=4%40dis%21EUR%2146.11%2143.39%21%21%2149.77%2146.83%21%40213bf77217253077305741385e1fa2%2112000041359500004%21rec%21DE%21%21ABXZ&utparam-url=scene%3ApcDetailTopMoreOtherSeller%7Cquery_from%3A)

Or is there something against this version?

**Comment by ChrGri** [comment]
Thank you. Looks good. Will add the link to the repo.

BR
