### ISSUE TITLE
Request:  CAD models in STEP format

### ISSUE THREAD

**Issue by eric-schleicher** [ChrGri/DIY-Sim-Racing-FFB-Pedal-Mechanical-Design#4]
Would it be possible to (additionally) publish the CAD geometries in STEP format?  F3d is a paid commercial CAD solution with 0 interoperability with other CAD tools.

**Comment by ChrGri** [comment]
Thank you for the request. The file has been uploaded [here](https://github.com/ChrGri/DIY-Sim-Racing-FFB-Pedal-Mechanical-Design/blob/main/CAD/DiyFfbPedalAssembly%20v78.step).

Therefore closing the issue. Feel free to reopen if anything is missing.

BR


__________________________________________________________________________________________
<a href="https://www.buymeacoffee.com/Captainchris"><img src="https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png" height="20px"></a>
