### ISSUE TITLE
Wrong link to servo debug port connector

### ISSUE THREAD

**Issue by martinhoyer** [ChrGri/DIY-Sim-Racing-FFB-Pedal-Mechanical-Design#6]
Looks like it was introduced in [fa65fb7](https://github.com/ChrGri/DIY-Sim-Racing-FFB-Pedal-Mechanical-Design/commit/fa65fb759df5681ed7c45371a627f18b62437a5e#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L197)- the link points to bearings, not connectors, which are at: https://www.aliexpress.com/item/1005005418641238.html

**Comment by ChrGri** [comment]
Thanks for the report. Closing this issue with a commit to fix.
