### ISSUE TITLE
pedal kinematic calculation error

### ISSUE THREAD

**Issue by dallehellstrom** [ChrGri/DIY-Sim-Racing-FFB-Pedal-Mechanical-Design#7]
If I have the linear guide as far forward as it can go and measure to the back of the linear guide I get the number 110 mm, that is too big a number that I cannot enter into simhub kinematics (max 100mm) "pedal kinematic calculation error" 

Simhub:
![Skärmbild (4)](https://github.com/user-attachments/assets/4cdc2dc7-3c0e-4719-9de8-90342d0b5368)

data on the current linear guide and the model I ordered
![IMG_7370](https://github.com/user-attachments/assets/848f437c-32ff-4250-85c8-560a3d2b2e85)

![IMG_7366](https://github.com/user-attachments/assets/ece2788e-13fb-4716-8654-35d609efb940)

**Comment by ChrGri** [comment]
Fixed with https://github.com/ChrGri/DIY-Sim-Racing-FFB-Pedal/commit/093751e91e8cdf91f4e09008380e3ef64e7bd885. 

https://github.com/user-attachments/assets/1774331c-a27e-485d-8428-d4a2fff2f158

Will be available in the next release.

BR
